### ISSUE TITLE
Custom highlighting not working

### ISSUE THREAD

**Issue by Moshem123** [tiagofumo/vim-nerdtree-syntax-highlight#41] opened 2020-10-24 13:04 UTC
I want to highlight exact matches for files with the name `Jenkinsfile`.
My configuration:
```
...
Plug 'preservim/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
Plug 'ryanoasis/vim-devicons'
...

let g:NERDTreeLimitedSyntax = 0
let g:NERDTreeHighlightFolders = 1
let g:NERDTreeHighlightFoldersFullName = 1
let g:NERDTreeExactMatchHighlightColor = {}
let g:NERDTreeExactMatchHighlightColor['.gitignore']  = 'EE6E73'
let g:NERDTreeExactMatchHighlightColor['Jenkinsfile'] = '834F79'
let g:NERDTreeSyntaxEnabledExactMatches = ["Jenkinsfile"]
```

Jenkinsfile is not highlighted:
![image](https://user-images.githubusercontent.com/17252601/97082435-49e68a80-1612-11eb-83dc-4efd5923236e.png)

Output of:
```
echo g:NERDTreeExactMatchHighlightColor

{
  ".bashprofile": "FFFFFF",
  ".bashrc": "FFFFFF",
  ".ds_store": "FFFFFF",
  ".gitconfig": "FFFFFF",
  ".gitignore": "EE6E73",
  ".gitlab-ci.yml": "D4843E",
  ".gvimrc": "8FAA54",
  ".vimrc": "8FAA54",
  ".zshrc": "FFFFFF",
  "Jenkinsfile": "834F79",
  "_gvimrc": "8FAA54",
  "_vimrc": "8FAA54",
  "cmakelists.txt": "FFFFFF",
  "docker-compose.yml": "689FB6",
  "dockerfile": "689FB6",
  "dropbox": "689FB6",
  "favicon.ico": "F09F17",
  "gruntfile.coffee": "F09F17",
  "gruntfile.js": "F09F17",
  "gruntfile.ls": "F09F17",
  "gulpfile.coffee": "CB6F6F",
  "gulpfile.js": "CB6F6F",
  "gulpfile.ls": "CB6F6F",
  "license": "FFFFFF",
  "makefile": "FFFFFF",
  "mix.lock": "FFFFFF",
  "node_modules": "8FAA54",
  "procfile": "834F79",
  "react.jsx": "689FB6",
  "typescript.jsx": "689FB6",
  "typescript.tsx": "689FB6"
}

```

**Comment by tiagofumo** [comment] 2020-10-24 16:02
Hi @Moshem123,

so, I don't know why but I think the vim-devicons plugin can't change the icon on a file named Jenkinsfile with exact match, so it has the default icon. Because of that the icon is not highlighted. An easy workaround is to use pattern match instead, adding this to your .vimrc:

```vimscript
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['Jenkinsfile'] = 'ICON' "see bellow
let g:NERDTreePatternMatchHighlightColor['Jenkinsfile'] = '834F79'
```

On linux `ctrl + shit + u` allows you to type an unicode value. Every one of these icons on NERDTree is actually an unicode character depending on the font you are using. In the font I am using there is a jenkins glyph with code e767, but it's too small, and hard to recognize. The icon that I use for config files is E615 which is a gear glyph. The default icon for files in my font is E612. You can check your font using [FontDrop](https://fontdrop.info/) and uploading your [nerdfonts](https://github.com/ryanoasis/nerd-fonts) file.

Result:
![image](https://user-images.githubusercontent.com/12556770/97086240-6c6baa00-15f8-11eb-8795-0be87b9c9236.png)

You could change the color for every default file icon but I don't think that's what you want. And because this bug is actually not caused by this plugin, I will close this issue. If you have any other questions, feel free to ask.

**Closed by tiagofumo** 2020-10-24 16:02 UTC

**Comment by Moshem123** [comment] 2020-10-24 18:18
@tiagofumo  thanks for your comment.
I managed to get the right icon, but I still can't figure out why it's not highlighted:
```
" Set icon for Jenkinsfile
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['Jenkinsfile'] = ''

" Highlight gitignore and Jenkinsfile
let g:NERDTreeExactMatchHighlightColor = {}
let g:NERDTreeExactMatchHighlightColor['Jenkinsfile'] = 'EE6E73'
" let g:NERDTreeSyntaxEnabledExactMatches = ["Jenkinsfile"]

let g:NERDTreePatternMatchHighlightColor = {}
let g:NERDTreePatternMatchHighlightColor['\..*ignore$'] = 'EE6E73'
```

And here's how it looks:
![image](https://user-images.githubusercontent.com/17252601/97089128-6c8e9880-163e-11eb-8019-a0bef94e04da.png)

**Comment by tiagofumo** [comment] 2020-10-24 18:24
This plugin uses the same variable you used for the icons. So as you used pattern match for vim-devicons you need to use pattern match for VNSH. You forgot this line:
```vim
" Highlight gitignore and Jenkinsfile
let g:NERDTreeExactMatchHighlightColor = {}
"let g:NERDTreeExactMatchHighlightColor['Jenkinsfile'] = 'EE6E73' "remove this line
let g:NERDTreePatternMatchHighlightColor['Jenkinsfile'] = 'EE6E73'
```

**Comment by Moshem123** [comment] 2020-10-24 18:36
Great!! Thank you so much.
I got everything working with:
```
" Set icon for Jenkinsfile
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols = {}
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['Jenkinsfile'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesPatternSymbols['\..*ignore.*'] = ''

let g:NERDTreePatternMatchHighlightColor = {}
let g:NERDTreePatternMatchHighlightColor['\..*ignore.*'] = 'EE6E73'
let g:NERDTreePatternMatchHighlightColor['Jenkinsfile'] = '62a2bf'
```

**Comment by tiagofumo** [comment] 2020-10-24 18:42
👍
