### ISSUE TITLE
Folder Icons turned pink

### ISSUE THREAD

**Issue by eprislac** [tiagofumo/vim-nerdtree-syntax-highlight#31] opened 2019-09-08 06:38 UTC
Is there any way to choose what color my directory folder icons render in? They turned pink with the latest update, and it's really bugging me.

**Comment by eprislac** [comment] 2019-09-08 06:48
<img width="188" alt="Screenshot 2019-09-08 01 47 27" src="https://user-images.githubusercontent.com/11530791/64484629-ae5e4480-d1da-11e9-98f4-33922c3aa6a0.png">

**Comment by tiagofumo** [comment] 2020-04-08 08:40
Hi, sorry for the long response time. This plugin only changes color of folders when one of them meets an exact match rule. As of now, the two rules that comes by default for folders are for the node_modules and the dropbox folders. Have you tried disabling the plugin and reopening vim to see if it changes anything?

**Comment by KarlWithK** [comment] 2020-05-19 22:10
Similar to this problem, all of my icons have turned pink and I am not sure why. Here is what this looks like: 
![image](https://user-images.githubusercontent.com/31679231/82383289-7e1ea500-99fb-11ea-98d0-9418f2c9dc3c.png).

My vimrc has:
```Plug 'scrooloose/nerdtree' "See dirs and files
Plug 'Xuyuanp/nerdtree-git-plugin' "git and nerd tree
Plug 'ryanoasis/vim-devicons' "Icons for plugins
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'"color for icons```

Sorry I am not sure where to report this problem I am facing. But changing my colorscheme doesn't work either.

**Comment by tiagofumo** [comment] 2020-05-19 22:52
I can't seem to be able to replicate this bug using the same plugins you did. Could you post all your config on pastebin or something? Also which version of vim and which OS are you using?

**Comment by KarlWithK** [comment] 2020-05-19 23:56
I am using archlinux, and mainly use neovim 0.4.3. However, I tested this on vim, and I get the same result. This is the pastebin with the full config: https://pastebin.com/X21f7Esn

And here is my vim run time tree if you need it:
![image](https://user-images.githubusercontent.com/31679231/82389628-b1b4fb80-9a0a-11ea-973b-8f63525d359a.png)

**Comment by tiagofumo** [comment] 2020-05-20 02:30
I see, if you disable this plugin (vim-nerdtree-syntax-highlight) and leave the other ones (vim-devicons and nerdtree-git-plugin) does the problem still happens? It seems to be the same color of your airline on the first picture.

**Comment by polyzen** [comment] 2020-05-20 03:39
https://github.com/ryanoasis/vim-devicons/issues/330

**Comment by KarlWithK** [comment] 2020-05-20 14:29
So, it's an issue with devicons itself. Should we close this issue?

**Comment by her** [comment] 2020-05-26 19:30
`vim-devicons` is using a more specific syntax match (`NERDTreeFlags`), which breaks this plugin integration. If this code was updated to move to `NERDTreeFlags` it should work again. See https://github.com/ryanoasis/vim-devicons/pull/332 for the full discussion that happened over here and why this PR was closed. 

Cheers y'all!

**Comment by tiagofumo** [comment] 2020-05-26 23:25
@her I updated the code as you said. Thanks for the tip

**Closed** 2020-05-26 23:25 UTC

**Comment by her** [comment] 2020-05-27 02:23
@tiagofumo that’s awesome! 🚀

**Comment by polyzen** [comment] 2020-05-27 04:20
The all icons being pink is fixed, but plain files and directories are still pink. Is that intentional?

**Comment by tiagofumo** [comment] 2020-05-27 04:23
@polyzen print please

**Comment by polyzen** [comment] 2020-05-27 04:46
![2020-05-27T00:37:20-04:00](https://user-images.githubusercontent.com/3533182/82978838-0b05c780-9fd5-11ea-81a0-e92f72a0a588.png)

**Comment by her** [comment] 2020-05-27 05:54
@polyzen try setting 

`:highlight NERDTreeDir ctermfg=0 guifg=#000000`

`NERDTreeDir` is the highlight group for those 🙂

**Comment by tiagofumo** [comment] 2020-05-27 08:53
@polyzen I just sent a new commit. Please try it out and see if it works for you.

**Comment by polyzen** [comment] 2020-05-27 18:17
Updated and the issue is resolved. :)
